#!/bin/sh

# Se crean los archivos en R
for f in *; do
	if [ -d $f ];
	then
		cp analisis.r "$f"/analisis_r.r;
	fi
done;

# Se ejecutan los archivos en R.
for f in *; do
	if [ -d $f ];
	then
		cd "$f";
		Rscript analisis_r.r > output.txt;
		cd ..;
	fi;
done;
