#!/bin/sh

cd ../3_DATA

# Se borran los archivos generados por el análisis en cada directorio.
for f in *; do
	if [ -d $f ];
	then
		cd "$f";
		rm 1_MODELOS.pdf analisis.r output.txt;
		cd ..;
	fi
done;
